parameters = {
    "sphinx": "5.1",
    "needs": 10,
    "needtables": 1,
    "needflows": 1,
    "needpies": 1,
    "needrefs": 1,
    "umls": 1,
    "dummies": 10,
    "pages": 10,
    "folders": 0,
    "depth": 1,
    "local": "",
    "parallel_read": True,
    "parallel_write": True,
}

info = {
    "#needs": "{{needs * page_amount}}",
    "#needtables": "{{needtables * page_amount}}",
    "#needflows": "{{needflows * page_amount}}",
    "#needpies": "{{needpies * page_amount}}",
    "needrefs": "{{needrefs * page_amount}}",
    "umls": "{{umls * page_amount}}",
    "#dummies": "{{dummies * page_amount}}",
    '#pages': "{{page_amount}}",
    '#indexes': "{{index_amount}}",
    '#folders': "{{folders ** depth}}",
}

references = {
    "small": {
        "sphinx": "5.1",
        "needs": 10,
        "needtables": 1,
        "needflows": 1,
        "needpies": 1,
        "needrefs": 1,
        "umls": 1,
        "dummies": 10,
        "pages": 5,
        "folders": 5,
        "depth": 1,
        "parallel_read": True,
        "parallel_write": True,
    },
    "medium": {
        "sphinx": "5.1",
        "needs": 10,
        "needtables": 1,
        "needflows": 1,
        "needpies": 1,
        "needrefs": 1,
        "umls": 1,
        "dummies": 10,
        "pages": 10,
        "folders": 5,
        "depth": 2,
        "parallel_read": True,
        "parallel_write": True,
    },
    "large": {
        "sphinx": "5.1",
        "needs": 30,
        "needtables": 1,
        "needflows": 1,
        "needpies": 1,
        "needrefs": 1,
        "umls": 1,
        "dummies": 50,
        "pages": 10,
        "folders": 5,
        "depth": 3,
        "parallel_read": True,
        "parallel_write": True,
    },
}